Repository triton-inference-server/core, pull requests merged in 2024-10, with the labels that each got.

#399 refactor: Allow ensemble to create the final response even if some of the outputs are not created
  src/ensemble_scheduler/ensemble_scheduler.cc
Labels: PR: refactor

#402 Allow missing ensemble output(s) (#399)
  src/ensemble_scheduler/ensemble_scheduler.cc
Labels: cherry-pick

#400 feat: Incorporate "additional-dependency-dirs"
  src/backend_manager.cc
  src/backend_manager.h
  src/shared_library.cc
  src/shared_library.h
Labels: PR: feat
