Repository triton-inference-server/core, pull requests merged in 2024-08, with the labels that each got.

#386 feat: Add histogram metric type
  include/triton/core/tritonserver.h
  src/metric_family.cc
  src/metric_family.h
  src/metrics.h
  src/test/metrics_api_test.cc
  src/tritonserver.cc
  src/tritonserver_stub.cc
Labels: enhancement

#389 feat: Add new histogram metric type (#386)
  include/triton/core/tritonserver.h
  src/metric_family.cc
  src/metric_family.h
  src/metrics.h
  src/test/metrics_api_test.cc
  src/tritonserver.cc
  src/tritonserver_stub.cc
Labels: cherry-pick

#388 feat: Load new model version should not reload loaded existing model version(s)
  src/model_config_utils.cc
  src/model_config_utils.h
  src/model_repository_manager/model_lifecycle.cc
  src/model_repository_manager/model_lifecycle.h
  src/model_repository_manager/model_repository_manager.cc
  src/model_repository_manager/model_repository_manager.h
Labels: PR: feat

#391 fix: Fix windows build
  src/tritonserver_stub.cc
Labels: bug

#392 fix: Fix windows build (#391)
  src/tritonserver_stub.cc
Labels: cherry-pick
